language: python
sudo: required
dist: xenial
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION wheel setuptools Cython pytest pytest-cov numpy scipy networkx jinja2 matplotlib coverage codecov
  - source activate test-environment
  - python setup.py install

script:
  - python setup.py build_ext -i
  - py.test -v --cov=pyiga --cov-report=xml
  - codecov

notifications:
  email: false
