language: python
sudo: required
dist: xenial
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION wheel setuptools Cython nose numpy scipy
  - source activate test-environment
  - conda install networkx
  - pip install pyamg
  - python setup.py install

script:
  python setup.py nosetests --verbosity=2

notifications:
  email: false
