image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "64"

init:
  - "ECHO Python %PYTHON_VERSION% %PYTHON_ARCH% bit"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe setup.py build_ext -i"
  - "%PYTHON%\\python.exe -m pip install pytest matplotlib"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -v"

after_test:
  # build the wheels
  - python setup.py bdist_wheel

artifacts:
  # bdist_wheel puts the built wheel in the dist directory
  - path: dist\*
